// Objective-C API for talking to github.com/triztian/mobilecpp Go package.
//   gobind -lang=objc github.com/triztian/mobilecpp
//
// File is generated by gobind. Do not edit.

#ifndef __Mobilecpp_H__
#define __Mobilecpp_H__

@import Foundation;
#include "Universe.objc.h"


/**
 * Concat ...
 */
FOUNDATION_EXPORT NSString* MobilecppConcat(NSString* a, NSString* b);

/**
 * Exception ...
 */
FOUNDATION_EXPORT NSString* MobilecppException(NSString* msg);

/**
 * Sum ...
 */
FOUNDATION_EXPORT long MobilecppSum(long a, long b);

#endif
