
// Objective-C API for talking to the following Go packages
//
//	github.com/triztian/mobilecpp
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Mobilecpp_FRAMEWORK_H__
#define __Mobilecpp_FRAMEWORK_H__

#include "Mobilecpp.objc.h"
#include "Universe.objc.h"

#endif
